#ifndef STATIC_VALUE_H
#define STATIC_VALUE_H

#define REGPATH "HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\GAMANIA\\MAPLESTORY"
#define REGPATH_OT "HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\GAMANIA\\MapleStory_TestServer"

#endif // STATIC_VALUE_H
